GET http://localhost:3000/problems/

###

GET http://localhost:3000/problems/5e42264641124618cb821aba

###

POST http://localhost:3000/problems/
Content-Type: application/json

{
    "name": "Blind 75",
    "problems": 
    [
        {
            "name": "Two Sum",
            "link": "https://leetcode.com/problems/two-sum/"
        },
        {
            "name": "Product of Array Except Self",
            "link": "https://leetcode.com/problems/product-of-array-except-self/"
        }
    ]
}

### 

DELETE http://localhost:3000/problems/5e42257b41124618cb821ab9